#!/usr/bin/env bash
set -e

function exists() {
  which $1 > /dev/null 2>&1
}

function fail() {
  echo $1
  echo "Please contact Lamassu support (support@lamassu.is), including "
  echo "command output and lamassu-debug.log file"
  exit 4
}

function upstart() {
  package="$1"

  cat > "/etc/init/$package"".conf" <<EOF
exec $package --key /root/$package\.key --cert /root/$package\.crt
respawn
start on startup
env DATABASE_URL=postgres://lamassu:$password@localhost/lamassu
env NODE_ENV=production
chdir $(npm -g explore $package pwd)
EOF
}

function initscript() {
  package="$1"

  cat > "/etc/init.d/$package" <<EOF
#!/bin/sh
### BEGIN INIT INFO
# Provides:          $package
# Required-Start:    \$remote_fs
# Required-Stop:     \$remote_fs
# Default-Start:     S
# Default-Stop:      
# Short-Description: $package
# Description:       Lamassu.is Operator Server
### END INIT INFO

export DATABASE_URL=postgres://lamassu:$password@localhost/lamassu
export NODE_ENV=production
PIDFILE=/var/run/$package.pid
DAEMON=/usr/local/bin/$package
DAEMON_OPTS="--key /root/$package.key --cert /root/$package.crt"

[ -x \$DAEMON ] || exit 0

case "\$1" in
        start)
                echo -n "Starting $package: "
                start-stop-daemon --start --quiet --pidfile \$PIDFILE --name $package --background --chdir $(npm -g explore $package pwd) --exec \$DAEMON -- \$DAEMON_OPTS
                echo "done."

        ;;
        stop)
                echo -n "Stopping $package: "
                start-stop-daemon --stop --quiet --pidfile \$PIDFILE --name $package 
                echo "done."
        ;;
        restart|reload|force-reload)
                \$0 stop
                \$0 start
        ;;
esac
EOF

  chmod 0700 "/etc/init.d/$package"
}


function prompt() {
  question="$1"
  default="$2"
  silent="$3"
  var="$4"

  echo -n "$question: "
  if [ ! -z "$default" ]; then
    echo -n "($default) "
  fi

  if [ "$silent" = true ]; then
    read -s result
    echo
  else
    read result
  fi

  if [ -z "$result" ]; then
    export "$var=$default"
  else
    export "$var=$result"
  fi
}

echo
echo "Hello! This script will install Lamassu Remote Server."
echo

if [ "$(whoami)" != "root" ]; then
  echo "This script has to be run as \`root\`"
  exit 3
fi

debug="lamassu-debug.log"
prefix="/usr/local"
arch=`uname -m`
case $arch in
	x86_64)
		arch=x64;;
	i686)
		arch=x86;;
esac
node="http://nodejs.org/dist/v0.10.26/node-v0.10.26-linux-$arch.tar.gz"

# First detect our package manager. Fail early if we don't support it.
update=""
install=""

rm -f lamassu-debug.log

if exists apt-get; then
  update="apt-get update -y"
  upgrade="apt-get upgrade -y"
  install="
    echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -c | awk '{print $2}')-pgdg main\" > /etc/apt/sources.list.d/pgdg.list &&
    curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - &&
    apt-get update -y &&
    apt-get install -y postgresql-9.3 libpq-dev git build-essential
  "
fi

if [ -z "$install" ]; then
  echo "Your package manager isn't supported"
  echo "This script currently supports apt-get"
  exit 1
fi

# Then detect our service management system. Also fail early if we don't
# support it.
# Remark: `upstart` appears to be going away from Ubuntu in lieu of `systemd`.
service=""

if exists start && [ -d "/etc/init" ]; then
  service="upstart"
fi

if exists /usr/sbin/update-rc.d; then
  service="debian_sysv-rc"
fi

if [ -z "$service" ]; then
  echo "Your service manager isn't supported"
  echo "This script currently supports upstart and debian_sysv-rc"
  exit 2
fi

echo "We'll now ask you a couple of questions in order to configure "
echo "this installation."
echo

echo "Pick your admin panel credentials:"
prompt "Username" "admin" false admin_username
prompt "Password" "" true admin_password


echo
echo "Updating your system (this might take a while)..."

eval $update >> $debug 2>&1 || fail "Updating your system failed"
eval $upgrade >> $debug 2>&1 || fail "Updating your system failed"

# Install PostgreSQL with the package manager we found.
echo
echo "Installing PostgreSQL (this might take a while)..."
eval $install >> $debug 2>&1 || fail "PostgreSQL installation failed"

# Set up users and databases in Postgres.
# Remark: do we want lamassu to be a super user?
password=$(openssl rand -hex 32)
su - postgres >> $debug 2>&1 <<EOF
  dropdb lamassu
  dropuser lamassu
  psql -c "CREATE ROLE lamassu WITH LOGIN SUPERUSER PASSWORD '$password';"
  createdb -O lamassu lamassu
EOF

echo "{\"postgresql\":\"postgres://lamassu:$password@localhost/lamassu\"}" > /etc/lamassu.json

echo "Fetching and installing node.js..."

# Install node in $prefix
curl "$node" 2>> $debug| tar -C"$prefix" --strip-components=1 -zxf- || fail "Node.js installation failed"

echo "Installing Lamassu stack (this might take a while)..."
# Install Lamassu stack

npm -g install lamassu-server lamassu-admin lamassu-scripts >> $debug 2>&1 || fail "Lamassu stack installation failed"

echo "Installing Lamassu services..."
if [ "$service" == "upstart" ]; then
  upstart "lamassu-server"
  upstart "lamassu-admin"
elif [ "$service" == "debian_sysv-rc" ]; then
  initscript "lamassu-server"
  initscript "lamassu-admin"
  update-rc.d lamassu-server defaults || fail "Initscript enabling failed"
  update-rc.d lamassu-admin defaults || fail "Initscript enabling failed"
fi

# Bootstrap lamassu database
# We also have to use `-h 127.0.0.1` because the default type of authentication
# for `local` connection is `peer`, which checks username of the user running
# `psql` command.
echo "Bootstrapping PostgreSQL..."
SQL_FILE="$(npm -g root)/lamassu-scripts/database/lamassu.sql"
PGPASSWORD="$password" psql -h 127.0.0.1 lamassu lamassu >> $debug 2>&1 < $SQL_FILE ||
	( echo "Could not connect to PostgreSQL as lamassu user.\nTry adding the following line to the beginning of your pg_hba.conf:"
	  echo "host lamassu lamassu 127.0.0.1 255.255.255.255 trust"
	  fail "Bootstrapping PostgreSQL failed" )

echo "Creating a Lamassu user account"
DATABASE_URL="postgres://lamassu:$password@localhost/lamassu" lamassu-useradd "$admin_username" "$admin_password" || fail "Adding a user failed"

ip=$(ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')

# Generate SSL certificates for lamassu-server and lamassu-admin.
echo "Generating SSL certificates..."
openssl req -new -newkey rsa:8092 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$ip:8081" -keyout /root/lamassu-admin.key  -out /root/lamassu-admin.crt >> $debug 2>&1 || fail "Generating a certificate for lamassu-admin failed"

openssl req -new -newkey rsa:8092 -days 9999 -nodes -x509 -subj "/C=US/ST=/L=/O=/CN=$ip:3000" -keyout /root/lamassu-server.key -out /root/lamassu-server.crt >> $debug 2>&1 || fail "Generating a certificate for lamassu-server failed"

chmod 600 /root/{*.key,*.crt}

echo "Starting Lamassu services..."
if [ "$service" == "upstart" ]; then
	start lamassu-admin >> $debug 2>&1 || fail "Starting lamassu-admin failed"
	start lamassu-server >> $debug 2>&1 || fail "Starting lamassu-server failed"
elif [ "$service" == "debian_sysv-rc" ]; then
	invoke-rc.d lamassu-admin start >> $debug 2>&1 || fail "Starting lamassu-admin failed"
	invoke-rc.d lamassu-server start >> $debug 2>&1 || fail "Starting lamassu-server failed"
fi

echo
echo "Done! Now it's time to configure Lamassu stack."
echo "Open https://$ip:8081 in your browser to access "
echo "your admin panel."
